spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  application:
    name: microcloud-config-client
  profiles: dev
---
server:
  port: 8202
spring:
  application:
    name: microcloud-config-client
  profiles: default
---
server:
  port: 8203
spring:
  application:
    name: microcloud-config-client
  profiles: beta
