spring:
  profiles:
    active: dev
---
server:
  port: 7001
spring:
  application:
    name: microcloud-test-dev
  profiles: dev

---
server:
  port: 7002
spring:
  application:
    name: microcloud-test-default
  profiles: default

---
server:
  port: 7003
spring:
  application:
    name: microcloud-test-beta
  profiles: beta