server:
  port: 8201
spring:
  application:
    name: microcloud-config-client
  profiles: dev
info:
  app.name: microcloud-config-dev
  company.name: cplatform
  app.version: v-dev-1.0
---
server:
  port: 8202
spring:
  application:
    name: microcloud-config-client
  profiles: default
info:
  app.name: microcloud-config-default
  company.name: cplatform
  app.version: v-default-1.0
---
server:
  port: 8203
spring:
  application:
    name: microcloud-config-client
  profiles: beta
info:
  app.name: microcloud-config-beta-10+
  company.name: cplatform-1024
  app.version: v-beta-11.0

