spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '{cipher}AQBH/LCfxlLskuABaottFUHRdp8CnhmmUgNU7HBx9bth1wU99YD2W3yW4XjFfi8U75WsHVQc6BE5HSjst0WadkLqR0BpzdSPzaJbgJb0aTP+pC/faPwapD/MnKpOc7pK1lzlhnGb958hD0lqx/p4SriIvILESRd0yx9utTuANGRtztMzyqdx1fUvsH7xmso6xDcSnACshWMeY7JcHfNytx5ydUGs5smEkNYiQUVxUz+YSIz5IVCuS8Xp8ne45lgQD3/+h86CdWvPoiRkWGOrCQI4IBmEizPA5LGFK33wC2nfsEbRPqj28Q1W0EHnWJPLC39crCY7l7d4zNpt4tOwkOcWJyHT1kZSQ5uM9Bt3/Yb6T+9lkUH3CmdL0wYWwMG3AoU='
    url: jdbc:mysql:///test8003
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      max-idle: 5  #数据库连接池的最大维持连接数
      max-total: 5 #最大的连接数
      max-wait-millis: 200  #等待连接获取的最大等待时间
  profiles: dev
  application:
    name: microcloud-config-dept-client
mybatis:
  config-location: classpath:mybatis.cfg.xml  #mybatis配置文件所在地
  type-aliases-package: com.cplatform.vo #mybatis操作类的别名所在包
  mapper-locations: classpath:com/cplatform/vo/mapper/*Mapper.xml  #mapper配置文件所在目录
eureka:
  client:
    service-url:
      defaultZone: http://edmindev:myjava@eureka-7001.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    instance-id: dept-8001.com
---
server:
  port: 8001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///test8003
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      max-idle: 5  #数据库连接池的最大维持连接数
      max-total: 5 #最大的连接数
      max-wait-millis: 200  #等待连接获取的最大等待时间
  profiles: beta
  application:
    name: microcloud-config-dept-client
mybatis:
  config-location: classpath:mybatis.cfg.xml  #mybatis配置文件所在地
  type-aliases-package: com.cplatform.vo #mybatis操作类的别名所在包
  mapper-locations: classpath:com/cplatform/vo/mapper/*Mapper.xml  #mapper配置文件所在目录
eureka:
  client:
    service-url:
      defaultZone: http://edminbeta:myjava@eureka-7002.com:7002/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    instance-id: dept-8001.com
